macOS space check

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -220,7 +220,7 @@ check_for_snap() {
 
 install-bash-completions() {
   if [[ "$OSTYPE" == "darwin"* ]]; then
-    echo "Skipping installation of tab completions (not supported on OSX)"
+    echo "Skipping installation of tab completions (not supported on macOS)"
   else
     if [ ! -f "$(pkg-config --variable=completionsdir bash-completion)/ethd" ]; then
       echo "Installing bash completions for ethd"
@@ -335,54 +335,73 @@ continue? (no/yes) " yn
 }
 
 
-space() {
+__get_docker_free_space() { # set __free_space to what's available to Docker
   if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
-    return
+    __free_space=$(dodocker run --rm -v macos-space-check:/dummy busybox df -P /dummy | awk '/[0-9]%/{print $(NF-2)}')
+  else
+    __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
+    __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
   fi
-
-  __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
-  __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
 
   re='^[0-9]+$'
   if ! [[ "${__free_space}" =~ $re ]] ; then
     echo "Unable to determine free disk space. This is likely a bug."
-    echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
+    if [[ "$OSTYPE" == "darwin"* ]]; then
+      echo "df reports $(dodocker run --rm -v macos-space-check:/dummy busybox df -P /dummy) and __free_space is ${__free_space}"
+    else
+      echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
+    fi
     exit 70
   fi
-  echo
-  echo "You have $(( __free_space / 1024 / 1024 )) GiB free on ${__docker_dir}"
+}
+
+
+__display_docker_dir() {
+  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
+    echo "Here's total and used space on Docker's virtual volume"
+    dodocker run --rm -v macos-space-check:/dummy busybox df -h /dummy
+  else
+    echo "Here's total and used space on ${__docker_dir}"
+    df -h "${__docker_dir}"
+  fi
+}
+
+
+__display_docker_volumes() {
   echo
   if [ -z "$(dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_[^_]+")" ]; then
     echo "There are no Docker volumes for this copy of ${__project_name}"
+    echo
   else
     echo "Here are the Docker volumes used by this copy of ${__project_name} and their space usage:"
     dodocker system df -v | grep -A 50 "VOLUME NAME" | grep "^$(basename "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"
+    echo
+    echo "If your Consensus Layer client takes more than 200 GiB, you can resync it with"
+    echo "\"${__me} resync-consensus\"."
+    echo
+  fi
+  echo "If there is some mystery space being taken up, try \"sudo ncdu /\"."
+  echo
+}
+
+
+space() {
+  __get_docker_free_space
+  echo
+  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
+    echo "You have $(( __free_space / 1024 / 1024 )) GiB free for Docker volumes"
+  else
+    echo "You have $(( __free_space / 1024 / 1024 )) GiB free on ${__docker_dir}"
   fi
   echo
-  echo "Here's the system output for total and used space on ${__docker_dir}"
-  df -h "${__docker_dir}"
-  echo
-  echo "If your Consensys Layer client takes more than 200 GiB of space, you can resync it with"
-  echo "\"${__me} resync-consensus\"."
-  echo
-  echo "If there is some mystery space being taken up, try \"sudo ncdu /\"."
+  __display_docker_dir
+  __display_docker_volumes
 }
+
 
 # Warn user if space is low, so they can prune
 check_disk_space() {
-  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
-    return
-  fi
-
-  __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
-  __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
-
-  re='^[0-9]+$'
-  if ! [[ "${__free_space}" =~ $re ]] ; then
-    echo "Unable to determine free disk space. This is likely a bug."
-    echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
-    exit 70
-  fi
+  __get_docker_free_space
 
   var="COMPOSE_FILE"
   value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" "${ENV_FILE}" || true)
@@ -404,7 +423,7 @@ check_disk_space() {
 # Literal match intended
 # shellcheck disable=SC2076
   if [[ "${value}" =~ "nethermind.yml" ]] && [[ "${__free_space}" -lt "${__min_free}" ]]; then
-    echo ""
+    echo
     echo "You are running Nethermind and have less than ${__min_gib} GiB of free disk space."
     if [ "${auto_prune}" = true ]; then
       echo "It should currently be auto-pruning, check logs with \"$__me logs -f --tail 500 execution | grep \
@@ -412,23 +431,9 @@ Full\". Free space:"
     else
       echo "If the below reads above ${__safe_prune} GiB free, prune it with \"$__me prune-nethermind\""
     fi
-    echo ""
-    df -h "${__docker_dir}"
-    echo ""
-    if [ -z "$(dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_[^_]+")" ]; then
-      echo "There are no Docker volumes for this copy of ${__project_name}"
-      echo
-    else
-      echo "Here are the Docker volumes used by this copy of ${__project_name} and their space usage:"
-      dodocker system df -v | grep -A 50 "VOLUME NAME" | grep "^$(basename "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"
-      echo
-      echo "If your Consensus Layer client takes more than 200 GiB, you can resync it with"
-      echo "\"${__me} resync-consensus\"."
-      echo
-    fi
     echo
-    echo "If there is some mystery space being taken up, try \"sudo ncdu /\"."
-    echo
+    __display_docker_dir
+    __display_docker_volumes
   elif [[ "${value}" =~ "geth.yml" ]] && [[ "${__free_space}" -lt 104857600 ]]; then
     echo
     echo "You are running Geth and have less than 100 GiB of free disk space."
@@ -436,66 +441,25 @@ Full\". Free space:"
     echo
     echo "Alternatively, if you don't feel ready for a resync and have more than 40 GiB free, you can prune \
 with \"$__me prune-geth\"."
-    echo ""
-    df -h "${__docker_dir}"
-    echo ""
-    if [ -z "$(dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_[^_]+")" ]; then
-      echo "There are no Docker volumes for this copy of ${__project_name}"
-      echo
-    else
-      echo "Here are the Docker volumes used by this copy of ${__project_name} and their space usage:"
-      dodocker system df -v | grep -A 50 "VOLUME NAME" | grep "^$(basename "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"
-      echo
-      echo "If your Consensus Layer client takes more than 200 GiB, you can resync it with"
-      echo "\"${__me} resync-consensus\"."
-      echo
-    fi
     echo
-    echo "If there is some mystery space being taken up, try \"sudo ncdu /\"."
-    echo
+    __display_docker_dir
+    __display_docker_volumes
   elif [[ "${value}" =~ "besu.yml" ]] && [[ "${__free_space}" -lt 52428800 ]]; then
     echo
     echo "You are running Besu and have less than 50 GiB of free disk space."
     echo
     echo "If this is a long-running Besu, you may prune trie-logs with \"$__me prune-besu\"."
-    echo
-    if [ -z "$(dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_[^_]+")" ]; then
-      echo "There are no Docker volumes for this copy of ${__project_name}"
-      echo
-    else
-      echo "Here are the Docker volumes used by this copy of ${__project_name} and their space usage:"
-      dodocker system df -v | grep -A 50 "VOLUME NAME" | grep "^$(basename "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"
-      echo
-      echo "If your Consensus Layer client takes more than 200 GiB, you can resync it with"
-      echo "\"${__me} resync-consensus\"."
-      echo
-    fi
-    echo
-    echo "If there is some mystery space being taken up, try \"sudo ncdu /\"."
+    __display_docker_volumes
     echo
   elif [[ "${__free_space}" -lt 52428800 ]]; then
-    echo ""
+    echo
     echo "You have less than 50 GiB of free disk space:"
-    echo ""
-    df -h "${__docker_dir}"
-    echo ""
+    echo
+    __display_docker_dir
+    echo
     echo "Pruning does not appear an option for your client mix."
     echo "If total space is less than 1.8 TiB, consider cloning to a larger drive."
-    echo ""
-    if [ -z "$(dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_[^_]+")" ]; then
-      echo "There are no Docker volumes for this copy of ${__project_name}"
-      echo
-    else
-      echo "Here are the Docker volumes used by this copy of ${__project_name} and their space usage:"
-      dodocker system df -v | grep -A 50 "VOLUME NAME" | grep "^$(basename "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"
-      echo
-      echo "If your Consensus Layer client takes more than 200 GiB, you can resync it with"
-      echo "\"${__me} resync-consensus\"."
-      echo
-    fi
-    echo
-    echo "If there is some mystery space being taken up, try \"sudo ncdu /\"."
-    echo
+    __display_docker_volumes
   fi
 }
 
@@ -808,10 +772,6 @@ delete_erigon() {
 
 
 upgrade_postgres() {
-  if [[ "$OSTYPE" == "darwin"* ]]; then # Can't check disk space on macOS and so can't do this safely
-    return
-  fi
-
   # Check for web3signer
   var="COMPOSE_FILE"
   value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" "${ENV_FILE}" || true)
@@ -858,22 +818,14 @@ upgrade_postgres() {
     return 70
   fi
 
-  __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
-  __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
-
-  re='^[0-9]+$'
-  if ! [[ "${__free_space}" =~ $re ]] ; then
-    echo "Unable to determine free disk space. This is likely a bug."
-    echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
-    return 70
-  fi
+  __get_docker_free_space
 
   if [[ "${__free_space}" -lt $(( (__source_size * 2) + 10485760 )) ]]; then
     echo
     echo "You don't have enough space free to migrate the database."
     echo "It is $(( __source_size / 1024 / 1024 )) GiB in size and you need twice as much free again."
     echo
-    df -h "${__docker_dir}"
+    __display_docker_dir
     echo
     return
   fi
@@ -1278,20 +1230,11 @@ update() {
     exit 1
   fi
 
-  if [[ ! "$OSTYPE" == "darwin"* ]]; then # Can't check disk space on macOS
-    __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
-    __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
-
-    re='^[0-9]+$'
-    if ! [[ "${__free_space}" =~ $re ]] ; then
-      echo "Unable to determine free disk space. This is likely a bug."
-      echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
-      exit 70
-    elif [ "${__free_space}" -lt 1048576 ]; then
-      echo "You have less than 1 GiB of space left on ${__docker_dir}."
-      echo "Aborting, as an update is not safe."
-      exit 1
-    fi
+  __get_docker_free_space
+  if [ "${__free_space}" -lt 1048576 ]; then
+    echo "You have less than 1 GiB of space left for Docker volumes."
+    echo "Aborting, as an update is not safe."
+    exit 1
   fi
 
   if [ -z "${ETHDSECUNDO-}" ]; then
@@ -1593,11 +1536,6 @@ attach-geth() {
 
 
 prune-geth() {
-  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
-    echo "Can't check Docker disk space on macOS and so can't safely prune."
-    return
-  fi
-
   __non_interactive=0
   while :
   do
@@ -1637,20 +1575,12 @@ prune-geth() {
     exit 1
   fi
 
-  __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
-  __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
-
-  re='^[0-9]+$'
-  if ! [[ "${__free_space}" =~ $re ]] ; then
-    echo "Unable to determine free disk space. This is likely a bug."
-    echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
-    exit 70
-  fi
+  __get_docker_free_space
 
   if [ "${__free_space}" -lt 41943040 ]; then
     echo "You do not have enough free disk space. Make sure this reads at least 40G free (Avail):"
-    df -h "${__docker_dir}"
-    echo ""
+    __display_docker_dir
+    echo
     echo "Aborting."
     exit 1
   fi
@@ -1703,7 +1633,7 @@ prune-geth() {
   if [ $__non_interactive = 0 ]; then
     echo "Geth PBSS is available. Consider answering \"No\" and using \"$__me resync-execution\" instead of prune."
     echo "PBSS continually prunes, making manual pruning runs a thing of the past."
-    echo ""
+    echo
     while true; do
       read -rp "WARNING - this will stop Geth and prune its database. Do you wish to continue? (No/Yes) " yn
       case $yn in
@@ -1713,20 +1643,20 @@ prune-geth() {
     done
   fi
 
-  echo ""
+  echo
   echo "Starting Geth prune"
-  echo ""
+  echo
   docompose run --rm set-prune-marker "touch /var/lib/goethereum/prune-marker"
   docompose stop execution && docompose rm -f execution
   start
-  echo ""
+  echo
   echo "Prune is running, you can observe it with '$__me logs -f execution'"
-  echo ""
+  echo
   echo "There should be three stages: \"Iterating state snapshot\", \"Pruning state data\", and \"Compacting \
 database\". During the \"Compacting database\" stage it may not output logs for an hour or so, that is normal."
-  echo ""
+  echo
   echo "When prune is done, which takes 4-5 hours, Geth will automatically start again."
-  echo ""
+  echo
 }
 
 
@@ -1829,11 +1759,6 @@ prune-besu() {
 
 
 prune-nethermind() {
-  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
-    echo "Can't check Docker disk space on macOS and so can't safely prune."
-    return
-  fi
-
   __non_interactive=0
   while :
   do
@@ -1873,15 +1798,7 @@ prune-nethermind() {
     exit 1
   fi
 
-  __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
-  __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
-
-  re='^[0-9]+$'
-  if ! [[ "${__free_space}" =~ $re ]] ; then
-    echo "Unable to determine free disk space. This is likely a bug."
-    echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
-    exit 70
-  fi
+  __get_docker_free_space
 
   var="NETWORK"
   NETWORK=$(sed -n -e "s/^${var}=\(.*\)/\1/p" "${ENV_FILE}" || true)
@@ -1896,7 +1813,8 @@ prune-nethermind() {
 
   if [ "${__free_space}" -lt ${__min_free} ]; then
     echo "You do not have enough free disk space. Make sure this reads at least ${__min_gib}G free (Avail):"
-    df -h "${__docker_dir}"
+    echo
+    __display_docker_dir
     echo
     echo "Aborting."
     exit 1
@@ -1953,9 +1871,9 @@ execution | grep Full\" to see whether it is."
     done
   fi
 
-  echo ""
+  echo
   echo "Starting Nethermind prune"
-  echo ""
+  echo
 
   set +e
   prune_result=$(docompose exec -T execution wget -qO- "http://localhost:1337" --header \
