Check for ethdo on send-address-change

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -1040,6 +1040,13 @@ keys() {
         echo "Copy the contents of ./.eth/ethdo to a USB drive, and prepare a Linux Live USB to safely enter your mnemonic."
         echo "Please see ./.eth/ethdo/README.md for details"
     elif [ "${1:-}" = "send-address-change" ]; then
+        var="COMPOSE_FILE"
+        value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" ".env" || true)
+        if [[ ! "${value}" =~ "ethdo.yml" ]]; then
+            echo "Please make sure ethdo.yml is part of COMPOSE_FILE in .env"
+            echo "Without it, this step cannot be run"
+            exit 1
+        fi
         docompose run --rm ethdo validator credentials set --timeout 2m
     else
         docompose run --rm -e OWNER_UID="${__owner_uid}" validator-keys "$@"
