No disk space check on macOS (#1743)

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -336,6 +336,10 @@ continue? (no/yes) " yn
 
 
 space() {
+  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
+    return
+  fi
+
   __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
   __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
 
@@ -366,6 +370,10 @@ space() {
 
 # Warn user if space is low, so they can prune
 check_disk_space() {
+  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
+    return
+  fi
+
   __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
   __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
 
@@ -800,6 +808,10 @@ delete_erigon() {
 
 
 upgrade_postgres() {
+  if [[ "$OSTYPE" == "darwin"* ]]; then # Can't check disk space on macOS and so can't do this safely
+    return
+  fi
+
   # Check for web3signer
   var="COMPOSE_FILE"
   value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" "${ENV_FILE}" || true)
@@ -1266,18 +1278,20 @@ update() {
     exit 1
   fi
 
-  __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
-  __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
+  if [[ ! "$OSTYPE" == "darwin"* ]]; then # Can't check disk space on macOS
+    __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
+    __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
 
-  re='^[0-9]+$'
-  if ! [[ "${__free_space}" =~ $re ]] ; then
-    echo "Unable to determine free disk space. This is likely a bug."
-    echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
-    exit 70
-  elif [ "${__free_space}" -lt 1048576 ]; then
-    echo "You have less than 1 GiB of space left on ${__docker_dir}."
-    echo "Aborting, as an update is not safe."
-    exit 1
+    re='^[0-9]+$'
+    if ! [[ "${__free_space}" =~ $re ]] ; then
+      echo "Unable to determine free disk space. This is likely a bug."
+      echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
+      exit 70
+    elif [ "${__free_space}" -lt 1048576 ]; then
+      echo "You have less than 1 GiB of space left on ${__docker_dir}."
+      echo "Aborting, as an update is not safe."
+      exit 1
+    fi
   fi
 
   if [ -z "${ETHDSECUNDO-}" ]; then
@@ -1579,6 +1593,11 @@ attach-geth() {
 
 
 prune-geth() {
+  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
+    echo "Can't check Docker disk space on macOS and so can't safely prune."
+    return
+  fi
+
   __non_interactive=0
   while :
   do
@@ -1810,6 +1829,11 @@ prune-besu() {
 
 
 prune-nethermind() {
+  if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
+    echo "Can't check Docker disk space on macOS and so can't safely prune."
+    return
+  fi
+
   __non_interactive=0
   while :
   do
