Nethermind prune initial attempt

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -710,13 +710,91 @@ prune-geth() {
     docompose stop execution && docompose rm -f execution
     start
     echo ""
-    echo "Prune is running, you can observe it with 'sudo ./ethd logs -f execution'"
+    echo "Prune is running, you can observe it with './ethd logs -f execution'"
     echo ""
     echo "There should be three stages: \"Iterating state snapshot\", \"Pruning state data\", and \"Compacting database\". During \
 the \"Compacting database\" stage it may not output logs for an hour or so, that is normal."
     echo ""
     echo "When prune is done, which takes 4-5 hours, Geth will automatically start again."
-    echo "NB: 'sudo' can be left off the './ethd logs' command if your user is part of the 'docker' group."
+    echo ""
+}
+
+prune-nethermind() {
+    __non_interactive=0
+    while :
+    do
+        if [ -z ${1+x} ]; then
+            break
+        fi
+        case "$1" in
+            --non-interactive)
+                __non_interactive=1
+                shift
+                ;;
+            *)
+                echo "Error: Unknown option: $1" >&2
+                exit 1
+                ;;
+        esac
+    done
+
+    if [ ! -f "./${ENV_FILE}" ]; then
+        echo "${ENV_FILE} configuration file not found, aborting."
+        exit 1
+    fi
+
+    if ! grep -q '^COMPOSE_FILE=.*nethermind\.yml' "${ENV_FILE}" 2>/dev/null ; then
+        echo "You do not appear to be using Nethermind, aborting."
+        exit 1
+    fi
+
+    rpc_line=$(grep '^EL_RPC_PORT=' "${ENV_FILE}")
+    regex='^EL_RPC_PORT=([0-9]+)'
+    if [[ ! "${rpc_line}" =~ ${regex} ]]; then
+        echo "Unable to determine EL_RPC_PORT, aborting."
+        exit 1
+    else
+        rpc_port="${BASH_REMATCH[1]}"
+    fi
+
+    sync_status=$(docompose exec -T execution wget -qO- "http://localhost:$rpc_port" --header 'Content-Type: application/json' --post-data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}')
+    exitstatus=$?
+    if [ $exitstatus -ne 0 ]; then
+        echo "Unable to connect to Nethermind: Is it running? Aborting."
+        exit 1
+    fi
+
+    if [[ ! "${sync_status}" =~ "false" ]]; then
+        echo "Nethermind is not done syncing yet. Sync status:"
+        echo "${sync_status}"
+        echo ""
+        echo "Aborting."
+        exit 1
+    fi
+
+    if [ $__non_interactive = 0 ]; then
+      while true; do
+          read -rp "WARNING - this will restart Nethermind and prune its database in the background. Do you wish to continue? (No/Yes) " yn
+          case $yn in
+              [Yy]es ) break;;
+              * ) echo "Aborting, no changes made"; exit 1;;
+          esac
+      done
+    fi
+
+    echo ""
+    echo "Starting Nethermind prune"
+    echo ""
+    docompose run --rm set-prune-marker "touch /var/lib/nethermind/prune-marker"
+    docompose stop execution && docompose rm -f execution
+    start
+    docompose run --rm set-prune-marker "curl -s --data {\\\"method\\\":\\\"admin_prune\\\",\\\"params\\\":[],\\\"id\\\":1,\\\"jsonrpc\\\":\\\"2.0\\\"} -H Content-Type:\ application/json http://execution:8545"
+    echo ""
+    echo "Prune is running, you can observe it with './ethd logs -f execution'"
+    echo ""
+    echo "Please do not restart the node or restart Nethermind until prune is done."
+    echo ""
+    echo "When prune is done, Nethermind will automatically re-start."
     echo ""
 }
 
