Kintsugi merge support

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -102,10 +102,10 @@ prune-geth() {
         exit 1
     fi
 
-    rpc_line=$(grep '^EC_RPC_PORT=' "${ENV_FILE}")
-    regex='^EC_RPC_PORT=([0-9]+)'
+    rpc_line=$(grep '^EL_RPC_PORT=' "${ENV_FILE}")
+    regex='^EL_RPC_PORT=([0-9]+)'
     if [[ ! "${rpc_line}" =~ ${regex} ]]; then
-        echo "Unable to determine EC_RPC_PORT, aborting."
+        echo "Unable to determine EL_RPC_PORT, aborting."
         exit 1
     else
         rpc_port="${BASH_REMATCH[1]}"
@@ -222,13 +222,13 @@ envmigrate() {
     if [ ! -f "./${ENV_FILE}" ]; then
         return
     fi
-    ALL_VARS=( COMPOSE_FILE EC_NODE EC_FALLBACK_NODE1 EC_FALLBACK_NODE2 GRAFFITI NETWORK EC_NETWORK \
+    ALL_VARS=( COMPOSE_FILE EL_NODE GRAFFITI NETWORK NETWORK_ID TOTAL_TERMINAL_DIFFICULTY ENODE ENR COINBASE \
              PRYSM_PEER_COUNT LH_PEER_COUNT TEKU_PEER_COUNT NIM_PEER_COUNT DOMAIN ACME_EMAIL \
              CF_EMAIL CF_API_TOKEN AWS_PROFILE AWS_HOSTED_ZONE_ID GRAFANA_HOST PRYSM_HOST \
-             EC_HOST EC_WS_HOST CC_HOST DDNS_SUBDOMAIN DDNS_PROXY TEKU_RAPID_SYNC LH_RAPID_SYNC LS_RAPID_SYNC  \
-	     NIMBUS_RAPID_SYNC CC_NODE BEACON_STATS_API BEACON_STATS_MACHINE EC_P2P_PORT LH_PORT PRYSM_PORT  \
+             EL_HOST EL_WS_HOST CL_HOST DDNS_SUBDOMAIN DDNS_PROXY TEKU_RAPID_SYNC LH_RAPID_SYNC LS_RAPID_SYNC  \
+	     NIMBUS_RAPID_SYNC CL_NODE BEACON_STATS_API BEACON_STATS_MACHINE EL_P2P_PORT LH_PORT PRYSM_PORT  \
 	     PRYSM_UDP_PORT NIM_PORT TEKU_PORT GRAFANA_PORT PRYSM_WEB_PORT TRAEFIK_WEB_PORT TRAEFIK_WEB_HTTP_PORT \
-	     EC_RPC_PORT EC_WS_PORT RESTART LOG_LEVEL GETH_CACHE SSV_P2P_PORT SSV_P2P_PORT_UDP )
+	     EL_RPC_PORT EL_WS_PORT RESTART LOG_LEVEL GETH_CACHE SSV_P2P_PORT SSV_P2P_PORT_UDP )
     TARGET_VARS=( NIM_SRC_BUILD_TARGET NIM_DOCKER_TAG NIM_DOCKERFILE TEKU_SRC_BUILD_TARGET TEKU_DOCKER_TAG \
                 TEKU_DOCKERFILE LH_SRC_BUILD_TARGET LH_DOCKER_TAG LH_DOCKERFILE PRYSM_SRC_BUILD_TARGET \
                 PRYSM_DOCKER_TAG PRYSM_DOCKERFILE ERIGON_SRC_BUILD_TARGET ERIGON_DOCKER_TAG ERIGON_DOCKERFILE \
@@ -279,15 +279,10 @@ query_network() {
     # Mainnet or Testnet network
     NETWORK=$(whiptail --notags --title "Select Network" --menu \
     "Which network do you want to run on?" 9 60 2 \
-    "prater" "Prater Testnet" \
-    "mainnet" "Ethereum Mainnet" 3>&1 1>&2 2>&3)
+    "kintsugi" "Kintsugi Merge Testnet" 3>&1 1>&2 2>&3)
 
-    if [ "${NETWORK}" == "mainnet" ]; then
-        EC_NETWORK=mainnet
-        echo "You chose to run on Ethereum mainnet"
-    elif [ "${NETWORK}" == "prater" ]; then
-        EC_NETWORK=goerli
-        echo "You chose to run on Prater testnet"
+    if [ "${NETWORK}" = "kintsugi" ]; then
+        echo "You chose to run on Kintsugi merge testnet"
     else
         echo "You chose Cancel."
         exit 0
@@ -298,17 +293,10 @@ query_deployment() {
     if uname -a | grep -q aarch64; then
       __deployment=$(whiptail --notags --title "Select deployment type" --menu \
       "What kind of deployment do you want to run?" 11 80 4 \
-      "node" "Ethereum node - consensus, execution and validator client" \
-      "rocket" "Validator client only - integrate with RocketPool" \
-      "validator" "Validator client only - integrate with other consensus layer" \
       "rpc" "Ethereum RPC node - consensus and execution client" 3>&1 1>&2 2>&3)
     else
       __deployment=$(whiptail --notags --title "Select deployment type" --menu \
       "What kind of deployment do you want to run?" 12 80 5 \
-      "node" "Ethereum node - consensus, execution and validator client" \
-      "rocket" "Validator client only - integrate with RocketPool" \
-      "validator" "Validator client only - integrate with other consensus layer" \
-      "blox" "Blox SSV node - consensus, execution and ssv-node" \
       "rpc" "Ethereum RPC node - consensus and execution client" 3>&1 1>&2 2>&3)
     fi
 
@@ -380,8 +368,7 @@ query_consensus_client() {
       "teku-base.yml" "Teku (Java) - consensus and validator client" \
       "lh-base.yml" "Lighthouse (Rust) - consensus and validator client" \
       "nimbus-base.yml" "Nimbus (Nim) - consensus and validator client" \
-      "lodestar-base.yml" "Lodestar (Javascript) - consensus and validator client" \
-      "prysm-base.yml" "Prysm (Go) - consensus and validator client" 3>&1 1>&2 2>&3)
+      "lodestar-base.yml" "Lodestar (Javascript) - consensus and validator client" 3>&1 1>&2 2>&3)
     fi
 
     exitstatus=$?
@@ -450,15 +437,12 @@ query_fallback_execution_client() {
 query_execution_client() {
     if uname -a | grep -q aarch64; then
       EXECUTION_CLIENT=$(whiptail --notags --title "Select execution client" --menu \
-      "Which execution client do you want to run?  Choose Custom for 3rd parties like Infura" 9 60 2 \
-      "NONE" "Custom" \
+      "Which execution client do you want to run?" 9 60 2 \
       "geth.yml" "Geth (Go)" 3>&1 1>&2 2>&3)
     else
       EXECUTION_CLIENT=$(whiptail --notags --title "Select execution client" --menu \
-      "Which execution client do you want to run?  Choose Custom for 3rd parties like Infura" 12 60 5 \
-      "NONE" "Custom" \
+      "Which execution client do you want to run?" 12 60 5 \
       "geth.yml" "Geth (Go)" \
-      "erigon.yml" "Erigon (Go)" \
       "nm.yml" "Nethermind (.NET)" \
       "besu.yml" "Besu (Java)" 3>&1 1>&2 2>&3)
     fi
@@ -469,26 +453,11 @@ query_execution_client() {
         exit 0
     fi
 
-    if [ "${EXECUTION_CLIENT}" == "NONE" ]; then
-        unset EXECUTION_CLIENT
-        query_custom_execution_client
-        EC_NODE="${EC_CUSTOM_NODE}"
+    echo "Your execution client file is:" "${EXECUTION_CLIENT}"
+    if [ "${CONSENSUS_CLIENT}" == "nimbus-base.yml" ]; then
+        EL_NODE="ws://execution:8546"
     else
-        echo "Your execution client file is:" "${EXECUTION_CLIENT}"
-        if [ "${CONSENSUS_CLIENT}" == "nimbus-base.yml" ]; then
-            EC_NODE="ws://execution:8546"
-        else
-            EC_NODE="http://execution:8545"
-        fi
-    fi
-    EC_FALLBACK_NODE1="${EC_NODE}"
-    EC_FALLBACK_NODE2="${EC_NODE}"
-
-    if (whiptail --title "Select Option" --yesno "Do you want to use a fallback execution client?" 10 60) then
-        query_fallback_execution_client
-        if [[ "${CONSENSUS_CLIENT}" != "prysm-base.yml" && "${CONSENSUS_CLIENT}" != "nimbus-base.yml" ]]; then
-            EC_NODE="${EC_NODE}"",""${EC_FALLBACK_NODE1}"
-        fi
+        EL_NODE="http://execution:8545"
     fi
 }
 
@@ -567,6 +536,18 @@ query_rapid_sync() {
     esac
 }
 
+query_coinbase() {
+        COINBASE=$(whiptail --title "Configure coinbase" --inputbox "What is the address you want transaction rewards to be sent to? (right-click to paste)" 10 60 3>&1 1>&2 2>&3)
+
+        exitstatus=$?
+        if [ $exitstatus -eq 0 ]; then
+            echo "your rewards address is:" $COINBASE
+        else
+            echo "You chose Cancel."
+            exit 0
+        fi
+}
+
 set_value_in_env() {
     # Assumes that "var" has been set to the name of the variable to be changed
     if [ "${!var+x}" ]; then
@@ -620,21 +601,22 @@ config () {
     esac
 
     if [[ ! "${CONSENSUS_CLIENT}" =~ "-validator.yml" ]]; then
-        CC_NODE="http://consensus:5052"
+        CL_NODE="http://consensus:5052"
 
         if [ ${__deployment} = "node" ]; then
           query_graffiti
         fi
         query_execution_client
         query_grafana
-        query_rapid_sync
+	query_coinbase
+#        query_rapid_sync
     else
         unset EXECUTION_CLIENT
         unset GRAFANA_CLIENT
 
         query_graffiti
         query_remote_beacon
-        CC_NODE="${REMOTE_BEACON}"
+        CL_NODE="${REMOTE_BEACON}"
     fi
 
     COMPOSE_FILE="${CONSENSUS_CLIENT}"
@@ -656,7 +638,7 @@ config () {
 
     var=GRAFFITI
     set_value_in_env
-    var=CC_NODE
+    var=CL_NODE
     set_value_in_env
     var=TEKU_RAPID_SYNC
     set_value_in_env
@@ -670,15 +652,11 @@ config () {
 #    set_value_in_env
     var=COMPOSE_FILE
     set_value_in_env
-    var=EC_NODE
-    set_value_in_env
-    var=EC_FALLBACK_NODE1
-    set_value_in_env
-    var=EC_FALLBACK_NODE2
+    var=EL_NODE
     set_value_in_env
     var=NETWORK
     set_value_in_env
-    var=EC_NETWORK
+    var=COINBASE
     set_value_in_env
 
     if [ ${__deployment} = "rocket" ]; then
